name: Tests

on:
  push:
    branches: ['master']

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test
